#!/usr/bin/python3

import asyncio
import json
import requests
import argparse

def getmyip_http():
    resp = requests.get('http://ipinfo.io/json')
    if resp.status_code != 200:
        raise ValueError('GET error {}'.format(resp.status_code))
    parsed_body = resp.json()
    return f'{parsed_body["ip"]} ({parsed_body["city"]}, {parsed_body["region"]}, {parsed_body["country"]})'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Retrieve my ip address')
    _args = parser.parse_args()
    print(getmyip_http())
